
const errorServer = async(err, req, res, next) => {
    
    console.log("*** INICIO DE ERROR ***");
    console.log(`PETICIÃ“N FALLIDA: ${req.method} a la url ${req.originalUrl}`);
    console.log(err);
    console.log("*** FIN DE ERROR ***");
    
    if (err?.name === "ValidationError") {
      res.status(400).json(err);
    } else {
      res.status(500).json(err);
    }
}